### ISSUE TITLE
Json test return differs from elm-test

### ISSUE THREAD

**Issue by razzeee** [mpizenberg/elm-test-rs#101]
Hey,

the elm-test-rs `testCompleted` event is called `testsCompleted` in elm-test.

Was that a deliberate decision?

Cheers

**Comment by mpizenberg** [comment]
Damn, it certainly wasn't :(

**Comment by mpizenberg** [comment]
The error is here https://github.com/mpizenberg/elm-test-runner/blob/master/src/ElmTestRunner/Reporter/Json.elm#L75

I don't think anyone is relying on that difference but I shall ask before changing it.

**Comment by mpizenberg** [comment]
I think I'll change this back to `testCompleted` for compatibility with elm-test but that definitely will be a breaking change so version will up to 2.0.0. It would be great if we find all other necessary breaking change if you're trying integration into language server @razzeee .

**Comment by lydell** [comment]
You could also include _both_ properties to be able to ship without a breaking change?

**Comment by mpizenberg** [comment]
Indeed ... and only remove it on the next breaking change. Could slow down things a bit but maybe that's negligeable

**Comment by lydell** [comment]
I guess the language server could easily support both, too.

**Comment by mpizenberg** [comment]
Actually it's not that easy to return a duplicated event with both `testCompleted` and `testsCompleted`.

And regarding supporting both in the langage server, it's nice but I feel like the user base of elm-test-rs is so much smaller that it makes more sense to make the change there. As long as people are aware, I don't mind releasing a breaking change. Especially if the user base grows due to usage in the langage server. I would not want more people relying on the wrong output ^^.

I've asked on the slack and discord and pinged some users and I'll let you know how that goes.

**Comment by razzeee** [comment]
Sorry, my initial issue mixed up both sides, but you figured that out. :)

**Comment by mpizenberg** [comment]
Fixed in cae0cb9
Now waiting for some other coming PRs before making a new release.
