### ISSUE TITLE
Stand alone binary: resources

### ISSUE THREAD

**Issue by harrysarson** [mpizenberg/elm-test-rs#12]
Currently, if the current executable is not located within the elm-test-rs git repository it will fail. It would be really nice if we could distribute a standalone executable that folk could move around there filesystem without breaking.

I think we need to solve the following to enable this:

1. Compile templates into the binary using https://doc.rust-lang.org/std/macro.include_str.html
2. Download the elm source from the internet on first run of elm-test-rs and store them somewhere sensible on the filesystem (possibly using https://crates.io/crates/directories)

Both have downsides but I think they are worth it.

**Comment by harrysarson** [comment]
Downsides:

1. Bigger binaries. Changes to templates require recompilation.
2. Internet access required to run tests.

**Comment by mpizenberg** [comment]
So (1) is now done, we include templates with `include_str`.

I've just tried something for the elm source (2) which does not work. Ideally, the code in `elm/` is an independent elm package. As such we could just publish it and add a dependency to `mpizenberg/elm-test-runner` when generating the `elm.json` of the runner. This could be quite nice since it would naturally take advantage of elm packages cache and not require internet access if a test has already run.

There is one downside to the published package approach, we cannot make modifications of the code in `elm/` and test it locally. So I just tried to see if it would be possible to add a build step that would create/update the content of `~/.elm/0.19.1/packages/mpizenberg/elm-test-runner/1.0.0` with the content of `elm/`. I thought the elm binary would just look for that folder and read its dependencies directly inside `.../1.0.0/elm.json`. It seems however that instead, it gives an `INCOMPATIBLE DEPENDENCIES` error. Maybe that's because the `mpizenberg/elm-test-runner` package does not exist (yet)? Maybe if it did, that patch would work? Further experiments are needed!

**Comment by mpizenberg** [comment]
Niiice, I've just hijacked `~/.elm/0.19.1/packages/mdgriffith/stylish-elephants/7.0.0` which is an existing package, with the content of `elm/` and it seems to work when adding a dependency to `mdgriffith/stylish-elephants@7.0.0` in the generated `elm.json` for `Runner.elm` :)

**Comment by harrysarson** [comment]
I got quite handy hacking installed elm packages whilst playing with elm/core. You have to be slightly careful with the elm compiler caches (data.dat) in elm_home and of course elm-stuff but on the whole it works pretty nicely.

**Comment by mpizenberg** [comment]
The thing I'm currently doing nukes entirely the `.../7.0.0` directory, including the `artifacts.dat` inside, and replaces the contents with the contents of `elm/` (minus its elm-stuff). That doesn't seem like something very careful XD. Am I in trouble? This seems to work ... but maybe that's because I've not interacted much with other things.

**Comment by harrysarson** [comment]
Yeah that works! Issues are

- Other packages that depend on the packag your are hacking can break (not a problem)
- do delete elm_stuff

But I think you are pretty safe 👍

**Comment by mpizenberg** [comment]
All good with the strategy of publishing the elm code as [`mpizenberg/elm-test-runner`](https://github.com/mpizenberg/elm-test-runner) and working locally on up-to-date modifications thanks to a [build step](https://github.com/mpizenberg/elm-test-rs/blob/aa75d6d28cfef72d93ba7a3aa6d271902498d38c/build.rs) copying the content of `elm/` inside `~/.elm/...`.
