### ISSUE TITLE
Debug.log not being captured

### ISSUE THREAD

**Issue by ceddlyburge** [mpizenberg/elm-test-rs#126]
Hi Matthieu, I am using elm-test-rs and the debug output is not being shown in the console. Are there any prerequisites or setup or anything that I need to do?
Cheers, Cedd

**Comment by ceddlyburge** [comment]
Actually I think I was using Debug.log in the wrong way. I'm confused as to why it compiled, but maybe I'll worry about that another day ...

**Comment by mpizenberg** [comment]
I think it may happen if your write `Debug.log myThing` instead of `Debug.log "myThing" myThing` but this isn't related to elm-test-rs specifically.
Also, this time specifically, if something gets into an infinite loop, the logs for the corresponding thing are never sent to the worker, so never reported
