### ISSUE TITLE
How to deal with exact dependencies of an application?

### ISSUE THREAD

**Issue by mpizenberg** [mpizenberg/elm-test-rs#19]
Most of the code for the runners and the reporter is classic elm code. In particular, all that code is currently contained inside the `elm/` folder of this repo and depends on a few other elm packages:
```js
        "billstclair/elm-xml-eeue56": "1.0.1 <= v < 2.0.0",
        "elm/core": "1.0.5 <= v < 2.0.0",
        "elm/json": "1.1.3 <= v < 2.0.0",
        "elm/random": "1.0.0 <= v < 2.0.0",
        "elm-explorations/test": "1.2.2 <= v < 2.0.0",
        "jorgengranseth/elm-string-format": "1.0.1 <= v < 2.0.0"
```
The problem is that to generate the tests, we have to fuse the application dependencies and the above ones of the test runner. So what should we do if the application says it depends on `"elm/core": "1.0.0"` for example? This is incompatible with the constraints for the test runner but it seems absurd to prevent testing because of that ...

**Comment by mpizenberg** [comment]
I'm not sure what the exact behavior of node-test-runner is. It seems that it always installs the newest versions for core, json, time, random. And for the rest it seems to prioritize the app-specified versions, but not to enforce them.

**Comment by mpizenberg** [comment]
In node-test-runner, the behavior is the one of  [`elm-json solve --test --extra elm/core elm/json elm/time elm/random`](https://github.com/rtfeldman/node-test-runner/blob/dafa12e58043915bdd8fcd7d2231ccff511a7827/lib/Solve.js#L44-L67). Concretely in the elm-json code, it's handled as follows. For every dependency of the app, except those listed in extra, add a constraint for exactly the version specified. Then add all the constraints specified in the extra parameters. So this means that the constraints for elm/core, elm/json, elm/time and elm/random specified in the app dependencies are completely ignored, and the others are respected or an error is reported if impossible.

For example, if I have a simple app that depends on elm/core 1.0.0, and I use `elm-json solve --extra elm/file` this will fail because elm/file depends on elm/core >= 1.0.1 and my app depends on elm/core 1.0.0.

**Comment by avh4** [comment]
Hmm, I guess this should maybe be an error, or at very least, a warning if the solved dependencies includes a version that conflicts with what the application says.  I think in the real world this will break down into two scenarios:
- there is a newer minor or patch version that some test library depends on.  In this case, in practice, it's almost always going to be safe for the app developer to upgrade to the minimal version.  And if it's not safe for their particular scenario, then that would mean their tests wouldn't be valid because the tests would be running with different behavior than their production code.  So I think it'd be okay to force people in that situation to upgrade their dependency version.
- or there is a newer major version that some test library depends on.  In this case, there's not really much they can do.  They just can't use that test dependency until they upgrade their app to the new major version.

So I think in both cases, the right thing to do is probably to give an error.

**Comment by mpizenberg** [comment]
Now keeping the exact constraint for applications. The dependencies of the code inside `elm/` is literally compatible with any 0.19 code at the moment thanks to updated dependencies. Let's re-assess this problem later if it reappears.
